[package]
name = "populate"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
redis = "1.0.1"
rust-s3 = "0.37.1"
tokio = { version = "1.48.0", features = ["full"] }
futures = "0.3"
